	<?php
	/*
	Template Name: Symposium
	*/

	get_header();

	?>

	<!-- html goes here -->

	<div id="mfadt-symposium" class="container">
		<div class="sixteen columns below-hero-content">

			<p class="symposium-title">Symposium</p>
			<p class="symposium-saturday">Theresa Lang Student & Community Center<br>
55 West 13th Street, New York City
			</p>
			<p class="symposium-title">panels</p>
		</div>
		
		<div id="panels-storytelling" class="four columns below-hero-content panels">
			<div class="wtf-mozilla">
			<p class="symposium-panel-title-storytelling">Storytelling</p>
			Conveying stories in a variety of forms, involving their audience and participants to different degrees. In some of these projects, the audience is recipient of the story; in others, the participants become a part of the narrative.</div>
		</div>
		<div id="panel-bigdata" class="four columns below-hero-content panels">
			<div class="wtf-mozilla">
			<p class="symposium-panel-title-really-big-data">Really Big Data</p>
			Tapping into the swarm of data generated by us and surrounding us, commenting on the role of the massive amount of often-hidden detail that exists.</div>
		</div>
		<div id="panels-play" class="four columns below-hero-content panels">
			<div class="wtf-mozilla">
			<p class="symposium-panel-title-play">Play</p>
			Inviting the audience to participate and explore. Some are toys that invite open-ended play; others are games with formalized rules, winning, and losing.</div>
		</div>
		<div id="panels-education" class="four columns below-hero-content panels">
			<div class="wtf-mozilla">
			<p class="symposium-panel-title-education">Education</p>
			Approaching the world of education through innovation – illuminating topics through demonstration, visualization, and participation. Some are geared toward children, while certain projects aim to broaden the knowledge of adults.</div>
		</div>

		<div id="panels-critical" class="four columns below-hero-content panels">
			<div class="wtf-mozilla">
			<p class="symposium-panel-title-critical-speculative">Critical & Speculative</p>
			Speculating over near or far future scenarios. Critiquing our world through design. Questioning current social practices or directions in which we may be moving.</div>
		</div>
		<div id="panels-experiential" class="four columns below-hero-content panels">
			<div class="wtf-mozilla">
			<p class="symposium-panel-title-experiential">Experiential</p>
			Enveloping the audience, immersing them in space and exploring the intersection of the physical and digital worlds.
			</div>
		</div>
		<div id="panels-information" class="four columns below-hero-content panels">
			<div class="wtf-mozilla">
			<p class="symposium-panel-title-information-instruments">Information Instruments</p>
			Conveying, managing and understanding information – presenting it to audiences in unique ways.</div>
		</div>
		<div id="panels-social" class="four columns below-hero-content panels">
			<div class="wtf-mozilla">
			<p class="symposium-panel-title-social">Social</p>
Exploring the ways in which we connect, creating new forms of communication and collaboration.</div>
		</div>

			<div class="eight columns below-hero-content friday">
<div class="six columns below-hero-content panels">
						<div class="symposium-panel-title">	
	<p class="symposium-saturday">Friday, May 16th<br>	
	 	
	</div>

	<div class="symposium-panel-title-hours">
		<p class="symposium-saturday">2.00PM - 8.00PM<br>
		 
	</div>
	</div>
						<div class="six columns below-hero-content panels">
						<div class="symposium-welcome">
						Opening: <br>
						Majora Carter<br>	
						Break  
					</div>
					<div class="symposium-welcome-hours">
					2.00PM - 2.40PM<br><br>
					2.40PM - 2.45PM<br>
					</div>
				</div>


				<div class="six columns below-hero-content panels">
					<div id="experiential-1">

						<div class="symposium-panel-title">
						<p class="symposium-panel-title-experiential">Experiential 1</p>	
						</div>	
						<div class="symposium-panel-title-hours">	
							2.45PM - 3.33PM
						</div>

						<div class="symposium-feedback-break">
	Panel respondent: Joe Saavedra<br>				
	  				
	</div>

	<div class="symposium-students">
	Anantapa Thongtawach<br>						
	Norihito Yuki<br>								
	Jia Xu<br>									
	Tingjian Shen<br>								
	Yuanjin Z.<br>							
	Qiuyi W.<br>									
	Zixin W.<br>									
	Jason Lalor<br>								
	</div>

	<div class="symposium-hours">
	2.45PM - 2.49PM<br>
	2.51PM - 2.55PM<br>
	2.57PM - 3.01PM<br>
	3.03PM - 3.07PM<br>
	3.09PM - 3.13PM<br>
	3.15PM - 3.19PM<br>
	3.21PM - 3.25PM<br>
	3.27PM - 3.31PM<br>
	</div>

	<div class="symposium-feedback-break-hours">			
	3.33PM - 3.49PM<br>		
	3.49PM - 3.54PM<br>
	</div>

	</div> 
	</div>

	<div class="six columns below-hero-content panels">
	<div id="storytelling-2">
	<div class="symposium-panel-title">	
	<p class="symposium-panel-title-storytelling">Storytelling 2</p>
	</div>		
	<div class="symposium-panel-title-hours">		
	3.54PM - 4.02PM
	</div>
	<div class="symposium-feedback-break">
	Panel respondent: Nick Fortugno<br>					
	</div>	
	 
	<div class="symposium-students">							
	Sarah Wever<br>									
	Viktoria Hristova<br>					
	George Chang<br>								
	Yang F.<br>									
	</div>

	<div class="symposium-hours">
	4.02PM - 4.06PM<br>
	4.08PM - 4.12PM<br>
	4.14PM - 4.18PM<br>
	4.20PM - 4.24PM<br>
	</div>

	<div class="symposium-feedback-break-hours">				
	4.26PM - 4.36PM<br>						
	4.36PM - 4.41PM<br>
	</div>

	</div>
	</div>

	<div class="six columns below-hero-content panels">
	<div id="really-big-data">
	<div class="symposium-panel-title">	
	<p class="symposium-panel-title-really-big-data">Really Big Data</p>
	</div>

	<div class="symposium-panel-title-hours">
	4.41PM - 5.05PM<br>
	</div>

	<div class="symposium-feedback-break">
	Panel respondent: Jen Lowe<br>						 								
	</div>
	 
	<div class="symposium-students">
	Albert Kim<br>								
	Jorge Proaño<br>							
	Gustavo Faria<br>						
	Apon Palanuwech<br>							
	</div>

	<div class="symposium-hours">
	4.41PM - 4.45PM<br>
	4.47PM - 4.51PM<br>
	4.53PM - 4.57PM<br>
	4.59PM - 5.03PM<br>
	</div>

	<div class="symposium-feedback-break-hours">					
	5.03PM - 5.11PM<br>							
	5.11PM - 5.14PM<br>
	</div>

	</div>
	</div>

	<div class="six columns below-hero-content panels">
	<div id="play-1">
	<div class="symposium-panel-title">	
	<p class="symposium-panel-title-play">Play 1</p>
	</div>
	<div class="symposium-panel-title-hours">
	5.14PM - 5.44PM<br>
	</div>

	 <div class="symposium-feedback-break">
	Panel respondent: Ramsey Nasser<br>						
	</div>	

	<div class="symposium-students">
	Anthony Marefat + Michael Kahane<br>					
	Matt G.<br>									
	Jennifer P.<br>								
	Joe Moore<br>								
	</div>

	<div class="symposium-hours">
	5.14PM - 5.24PM<br>
	5.26PM - 5.30PM<br>
	5.32PM - 5.36PM<br>
	5.38PM - 5.42PM<br>
	</div>	

	<div class="symposium-feedback-break-hours">					
	5.44PM - 5.54PM<br>						
	5.54PM - 6.01PM<br>
	</div>

	</div>
	</div>

	<div class="six columns below-hero-content panels">
	<div id="play-2">

	<div class="symposium-panel-title">	
	<p class="symposium-panel-title-play">Play 2</p>
	</div>

	<div class="symposium-panel-title-hours">
	6.01PM - 6.31PM<br>
	</div>

	<div class="symposium-feedback-break">
	Panel respondent: Chloe Varelidi<br>												
	</div>

	<div class="symposium-students">
	Tannaz E.<br>								
	Yu Yi C.<br>								
	Huy N.<br>									
	Jomkwan (Chy)<br>							
	Li-Wen Chang (Peter)<br>						
	</div>

	<div class="symposium-hours">
	6.01PM - 6.05PM<br>
	6.07PM - 6.11PM<br>
	6.13PM - 6.18PM<br>
	6.20PM - 6.24PM<br>
	6.26PM - 6.30PM<br>
	</div>
	
	<div class="symposium-feedback-break-hours">					
	6.32PM - 6.42PM<br>								
	6.42PM - 6.47PM<br>
	</div>

	</div>
	</div>

	<div class="six columns below-hero-content panels">
	<div id="education">
	<div class="symposium-panel-title">	
	<p class="symposium-panel-title-education">Education</p>
	</div>

	<div class="symposium-panel-title-hours">
	6.47PM - 7.27PM<br>
	</div>
	
	<div class="symposium-feedback-break">
	Panel respondent: Sara Chipps<br>					
	</div>

	<div class="symposium-students">
	Mauricio Sanchez<br>					
	Ricardo Mora<br>						
	Francesca Castelli<br>					
	Adiel F.<br>							
	Carla M.	<br>							
	Mehdi Salehi + Kristen Kersh<br>					
	Chloe Koo<br>						
	</div>

	<div class="symposium-hours">

	6.47PM - 6.51PM<br>
	6.53PM - 6.57PM<br>
	6.59PM - 7.03PM<br>
	7.05PM - 7.09PM<br>
	7.11PM - 7.15PM<br>
	7.17PM - 7.21PM<br>
	7.23PM - 7.27PM<br>
	</div>

	<div class="symposium-feedback-break-hours">				
	7.27PM - 7.43PM<br>
	</div>

	</div>
	</div>

	</div>

	<div class="eight columns below-hero-content saturday">

	<div class="six columns below-hero-content panels">

	<div class="symposium-panel-title">	
	<p class="symposium-saturday">Saturday, May 17th<br>
	 		
	</div>

	<div class="symposium-panel-title-hours">
		<p class="symposium-saturday">12.00PM - 7.00PM<br>
		 </div>
	</div>

	<div class="six columns below-hero-content panels">
	<div class="symposium-welcome">
	Welcome<br>	
	Break  				
	</div>
	<div class="symposium-welcome-hours">				
	12.00PM - 12.10PM<br>								
	12.10PM - 12.15PM<br>
	</div>
	</div>


	<div class="six columns below-hero-content panels">
	<div id="critical-speculative-1">

	<div class="symposium-panel-title">	
	<p class="symposium-panel-title-critical-speculative">Critical & speculative 1</p>
	</div>

	<div class="symposium-panel-title-hours">
	12.15PM - 12.51PM<br>
	</div>
	
	<div class="symposium-feedback-break">
	Panel respondent: Julia Kaganskiy<br>						
	  								
	</div>

	<div class="symposium-students">
	Bernardo S.<br>						
	Soo K.<br>				
	Fei L.<br>			
	Tiam Taheri<br>		
	Seungkyun L.<br>			
	Aneta Genova<br>			
	</div>

	<div class="symposium-hours">
	12.15PM - 12.19PM<br>
	12.21PM - 12.25PM<br>
	12.27PM - 12.31PM<br>
	12.33PM - 12.37PM<br>
	12.39PM - 12.43PM<br>
	12.45PM - 12.59PM<br>
	</div>

	<div class="symposium-feedback-break-hours">				
	12.51PM - 1.03PM<br>								
	1.03PM - 1.08PM<br>
	</div>

	</div>
	</div>

	<div class="six columns below-hero-content panels">
	<div id="critical-speculative-2">

	<div class="symposium-panel-title">	
	<p class="symposium-panel-title-critical-speculative">Critical & speculative 2</p>
	</div>

	<div class="symposium-panel-title-hours">
	1.08PM - 1.50PM<br>
	</div>

	<div class="symposium-feedback-break">
	Panel respondent: Ted Byfield<br>
	  
	</div>
	 

	<div class="symposium-students">
	Napangsiri (Siri) W.	<br>				
	Veronica B.<br>				
	Mirte B.	<br>				
	Morgan F.<br>				
	Haijing Liu<br>				
	Min Sung Kwak + Jungyeon Kim<br>			
	Mennie Hsiu Ying Shen<br>			
	</div>

	<div class="symposium-hours">
	1.08PM - 1.12PM<br>
	1.14PM - 1.18PM<br>
	1.20PM - 1.24PM<br>
	1.26PM - 1.30PM<br>
	1.32PM - 1.36PM<br>
	1.38PM - 1.42PM<br>
	1.44PM - 1.48PM<br>
	</div>

	<div class="symposium-feedback-break-hours">
	1.50PM - 2.04PM<br>
	2.04PM - 2.09PM<br>
	</div>
	</div>
	</div>

	<div class="six columns below-hero-content panels">
	<div id="storytelling-1">

	<div class="symposium-panel-title">	
	<p class="symposium-panel-title-storytelling">Storytelling 1</p>
	</div>

	<div class="symposium-panel-title-hours">
	2.09PM - 2.39PM<br>
	</div>
	
		<div class="symposium-feedback-break">
	Panel respondent: Brett Renfer<br>
	  
	</div>
	<div class="symposium-students">
	Jeannette Subero<br>				
	Bobby Fata<br>				
	Clarisa Diaz<br>				
	Sophie Kaars S.<br>			
	Salome Asega<br>			
	</div>

	<div class="symposium-hours">
	2.09PM - 2.13PM<br>
	2.15PM - 2.19PM<br>
	2.21PM - 2.25PM<br>
	2.27PM - 2.31PM<br>
	2.33PM - 2.37PM<br>
	</div>

	<div class="symposium-feedback-break-hours">
	2.39PM - 2.49PM<br>
	2.49PM - 2.54PM<br>
	</div>	
	</div>
	</div>

	<div class="six columns below-hero-content panels">
	<div id="experiential-2">

	<div class="symposium-panel-title">	
	<p class="symposium-panel-title-experiential">Experiential 2</p>
	</div>

	<div class="symposium-panel-title-hours">
	2.54PM - 3.42PM<br>
	</div>
		<div class="symposium-feedback-break">
	Panel respondent: Ryan Raffa<br>	
	  			
	</div>	
	 
	<div class="symposium-students">
	Wenwen Li<br>				
	Ye Han<br>		
	Decho Pitukcharoen<br>				
	Jackie Simon<br>			
	Joori Lee<br>			
	Owen Herterich<br>				
	Matt Felsen<br>				
	Yi-Ning Huang<br>				
	</div>

	<div class="symposium-hours">
	2.54PM - 2.59PM<br>
	3.01PM - 3.05PM<br>
	3.07PM - 3.11PM<br>
	3.13PM - 3.17PM<br>
	3.19PM - 3.23PM<br>
	3.25PM - 3.29PM<br>
	3.31PM - 3.35PM<br>
	3.37PM - 3.41PM<br>
	</div>
							
	<div class="symposium-feedback-break-hours">
	3.42PM - 3.58PM<br>						
	3.58PM - 4.03PM<br>
	</div>
	</div>
	</div>

	<div class="six columns below-hero-content panels">
	<div id="information-instruments">

	<div class="symposium-panel-title">	
	<p class="symposium-panel-title-information-instruments">Information Instruments</p>
	</div>

	<div class="symposium-panel-title-hours">
	4.03PM - 4.51PM<br>
	</div>
	 
	 <div class="symposium-feedback-break">
	Panel respondent: Manuel Lima<br>
	  	
	</div>		
	<div class="symposium-students">
	Justin Charles<br>				
	Susse Sonderby Jensen<br>				
	Kamilla Kielbowska<br>				
	Wenting Zhang<br>				
	Anthony Driscoll<br>				
	Alexandra Samuel<br>				
	Oriol Bella<br>				
	Patricio Gonzalez Vivo<br>				
	</div>

	<div class="symposium-hours">
	4.03PM - 4.07PM<br>
	4.09PM - 4.13PM<br>
	4.15PM - 4.19PM<br>
	4.21PM - 7.25PM<br>
	7.27PM - 7.31PM<br>
	7.33PM - 7.37PM<br>
	7.39PM - 7.43PM<br>
	7.45PM - 7.49PM<br>
	</div>
						
	<div class="symposium-feedback-break-hours">
	4.51PM - 5.07PM<br>			
	5.07PM - 5.12PM<br>
	</div>
	</div>
	</div>

	<div class="six columns below-hero-content panels">
	<div id="social">

	<div class="symposium-panel-title">	
	<p class="symposium-panel-title-social">Social</p>
	</div>

	<div class="symposium-panel-title-hours">
	5.12PM - 5.48PM<br>
	</div>
	
	<div class="symposium-feedback-break">
	Panel respondent: Liz Filardi<br>
	  
	</div>	

	<div class="symposium-students">
	Quincy Bock<br>			
	Aero Windwalker<br>			
	Ritika B.<br>	
	Or Leviteh<br>	
	Samir Naimi<br>		
	Sharouhz Vasabi<br>			
	</div>

	<div class="symposium-hours">
	5.07PM - 5.11PM<br>
	5.13PM - 5.17PM<br>
	5.19PM - 5.33PM<br>
	5.35PM - 5.39PM<br>
	5.42PM - 5.46PM<br>
	5.48PM - 5.52PM<br>
	</div>


	<div class="symposium-feedback-break-hours">
	5.52PM - 5.56PM<br>							
	5.58PM - 6.03PM<br>
	</div>

	</div>
	</div>

	<div class="six columns below-hero-content panels">
						<div class="symposium-welcome">
						Closing:<br>
						Emily Gobeille and<br> Theo Watson	
						  
					</div>
					<div class="symposium-welcome-hours">
					6.07PM - 7.00PM
					</div>
	</div>

	</div>
	</div>
	</section>


	<?php get_footer(); ?>
